{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opencost-ai.gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencost-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
automountServiceAccountToken: false
{{- end }}
